### PR TITLE
Create unit_test.py

### PR DESCRIPTION
**Pull request by uarif**
Created unit test file, maybe it will need some changes later.

### CODE REVIEW

**Comment by uarif** [comment]
Did some changes in the code

**Comment by uarif** [comment]
Actually, I added the assert statement.

**Comment by uarif** [comment]
The last file, used a different method and latter on I checked that the HW states that we should include assert.

**Comment by reshnashrestha** [comment]
Hi Arif , in you code, the expected periodic times provided in the test cases are incorrect according to the formula for a simple pendulum.

**Comment by uarif** [comment]
@reshnashrestha You are correct, thank you. But it is not finalized yet. 
Thanx anyway,

**Comment by reshnashrestha** [comment]
@uarif yeah. I tried to run this. Okay hope you fix it soon.

**Pull request merged**
